services:
  orchestrator:
    build: .
    container_name: ytcaption-orchestrator
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-8004}:${CONTAINER_PORT:-8000}"  # host:container
    volumes:
      - "${LOG_DIR:-./logs}:/app/logs"
      - "./artifacts:/app/artifacts"                  # útil p/ ver saídas
    networks:
      - ytcaption-network
    restart: unless-stopped
    healthcheck:
      # usa a porta interna do container (CONTAINER_PORT)
      test: ["CMD-SHELL", "python -c \"import os,sys,httpx; p=os.getenv('CONTAINER_PORT','8000'); r=httpx.get(f'http://localhost:{p}/health'); sys.exit(0 if r.status_code==200 else 1)\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ytcaption-network:
    name: ytcaption-network
