services:
  orchestrator:
    build: .
    container_name: ytcaption-orchestrator
    env_file:
      - .env
    # expõe a porta configurada no .env (fallback 8000)
    ports:
      - "${APP_PORT:-8000}:8000"
    # usa o diretório de logs indicado no .env (fallback ./logs) -> dentro do container é /app/logs
    volumes:
      - "${LOG_DIR:-./logs}:/app/logs"
    networks:
      - ytcaption-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ytcaption-network:
    external: true
    name: ytcaption-network
