global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'whisper-api-monitor'

# Alertmanager configuration (opcional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Regras de alerta (opcional)
rule_files:
  # - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Whisper API metrics
  - job_name: 'whisper-api'
    static_configs:
      - targets: ['whisper-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
