services:
  # 1) Redis
  redis:
    image: redis:6.2-alpine
    container_name: audio-normalization-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

  # 2) API
  audio-normalization-service:
    build: .
    container_name: audio-normalization-api
    ports:
      - "${PORT:-8001}:8001"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./temp:/app/temp
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    gpus: all            # << usar GPU no Compose clássico
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    labels:
      - "com.example.service=audio-normalization"
      - "com.example.version=2.0.0"

  # 3) Worker Celery
  celery-worker:
    build: .
    container_name: audio-normalization-celery
    command: python -m celery -A app.celery_config worker --loglevel=info --concurrency=1 --pool=solo --queues=audio_normalization_queue
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./temp:/app/temp
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - C_FORCE_ROOT=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    gpus: all            # << usar GPU no Compose clássico
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      audio-normalization-service:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "celery -A app.celery_config inspect ping --timeout=1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    labels:
      - "com.example.service=audio-normalization-worker"
      - "com.example.version=2.0.0"
