"""Constants for Audio Generation Service."""

# ===== JOB =====
JOB_ID_PREFIX = "ag_"
JOB_PREFIX = "ag_job:"
JOB_TTL_HOURS = 24
JOB_TTL_SECONDS = JOB_TTL_HOURS * 3600

# ===== VOICE =====
VOICE_ID_PREFIX = "vc_"
VOICE_PREFIX = "ag_voice:"
VOICE_INDEX_KEY = "ag_voices:all"

# ===== STAGES =====
STAGE_MODEL_LOADING = "model_loading"
STAGE_TEXT_CHUNKING = "text_chunking"
STAGE_AUDIO_GENERATION = "audio_generation"
STAGE_AUDIO_ASSEMBLY = "audio_assembly"

# ===== CELERY =====
CELERY_TASK_GENERATE_AUDIO = "generate_audio"
CELERY_QUEUE = "audio_generation_queue"
CELERY_MAX_RETRIES = 3
CELERY_SOFT_TIME_LIMIT = 2700
CELERY_TIME_LIMIT = 3600

# ===== AUDIO =====
VOICE_SAMPLE_RATE_TARGET = 24000
VOICE_CHANNELS_TARGET = 1
VOICE_FORMAT = "wav"
SUPPORTED_AUDIO_EXTENSIONS = frozenset({".wav", ".mp3", ".m4a", ".ogg"})
OUTPUT_AUDIO_FORMAT = "wav"

# ===== TTS DEFAULTS =====
DEFAULT_EXAGGERATION = 0.75
DEFAULT_CFG_WEIGHT = 0.35
DEFAULT_TEMPERATURE = 0.8
DRAMATIC_EXAGGERATION = 0.8
DRAMATIC_CFG_WEIGHT = 0.3
DRAMATIC_TEMPERATURE = 0.8
NEUTRAL_EXAGGERATION = 0.5
NEUTRAL_CFG_WEIGHT = 0.5
NEUTRAL_TEMPERATURE = 0.8

# ===== VALIDATION =====
AUDIO_VALIDATION_MIN_SNR_DB = 20.0
