version: '3.8'

services:
  video-downloader-service:
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - ytcaption-network

  celery-worker:
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - ytcaption-network

networks:
  ytcaption-network:
    external: true
    name: ytcaption-network