services:
  ytcaption-v3:
    build: .
    image: ytcaption-v3:latest
    container_name: ytcaption-v3
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=INFO
      - TIMEOUT_SECONDS=10
      - MAX_RETRIES=2
      - CONCURRENCY_LIMIT=4
      - CACHE_TTL_SECONDS=86400
      - CACHED_ONLY=false
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
    restart: unless-stopped
